AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: 'Function to process Lex events for OrderTicket chatbot. '
Resources:
  OrderTicketValidation:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs10.x
      CodeUri: .
      Description: 'Function to process Lex events for OrderTicket chatbot. '
      MemorySize: 128
      Timeout: 3
      Role: >-
        arn:aws:iam::083452710071:role/service-role/OrderTicketValidation-role-dccyy4w9
